In [ ]:
import numpy as np

np.set_printoptions(precision=0, suppress=True)

In [ ]:
edadMatriz =np.random.uniform(
  low=20,
  high=50,
  size=(3,3)
)
edadMatriz

array([[44., 36., 34.],
       [37., 36., 24.],
       [47., 42., 21.]])

In [ ]:
ingresosMatriz =np.random.uniform(
  low=2000,
  high=5000,
  size=(3,3)
)
ingresosMatriz

array([[3377., 3886., 3212.],
       [4331., 2769., 4466.],
       [4250., 4459., 3551.]])

In [ ]:
edadColumn =  edadMatriz.reshape(9)
edadColumn

array([44., 36., 34., 37., 36., 24., 47., 42., 21.])

In [ ]:
ingresosColumn =  ingresosMatriz.reshape(9)
ingresosColumn

array([3377., 3886., 3212., 4331., 2769., 4466., 4250., 4459., 3551.])

In [ ]:
combina = np.column_stack([edadColumn,ingresosColumn])
combina

array([[  44., 3377.],
       [  36., 3886.],
       [  34., 3212.],
       [  37., 4331.],
       [  36., 2769.],
       [  24., 4466.],
       [  47., 4250.],
       [  42., 4459.],
       [  21., 3551.]])

In [ ]:
edadMenorFiltro = edadColumn >= 20 
edadMayorFiltro = edadColumn <= 30 
edadFiltro = np.logical_and(edadMenorFiltro,edadMayorFiltro)
edadFiltro



array([False, False, False, False, False,  True, False, False,  True])

In [ ]:
edadMenorFiltro = columnIngresos >= 2000 
ingresoMayorFiltro = columnIngresos <= 5000
ingresoFiltro = np.logical_and(edadMenorFiltro,ingresoMayorFiltro)
ingresoFiltro


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
completoFiltro = np.logical_and(edadFiltro, ingresoFiltro)
combina[completoFiltro]

array([[  24., 4466.],
       [  21., 3551.]])